# Use the official Node.js image as the base image
FROM node:20

# Set the working directory inside the container
WORKDIR /usr

# Copy package.json and package-lock.json to the container
COPY package*.json ./

# Install project dependencies inside the container
RUN npm install

# Copy all application files to the container
COPY . .

# Expose the port your app will run on
EXPOSE 3000

# Command to run your application
CMD ["npm", "start"]
